# Statistical data analysis {#sda}

## Linear Regression

### A simple way to assess inference methods

> keywords: #regression, #linear, #inference, #cluster, #robust,  #differences-in-differences, #stratification

Article by Bruno Ferman ([Link](https://arxiv.org/pdf/1912.08772.pdf))

* **Abstract:** We propose a simple way to assess whether inference methods are reliable.  The assess-ment can detect problems when the asymptotic theory that justifies the inference method isinvalid and/or provides a poor approximation given the design of the empirical application.It can be easily applied to a wide range of applications.  We show that, despite being a simpleidea and despite its limitations, this assessment has the potential of substantially reducingthe number of papers that are published based on misleading inference, if it becomes widelyused by applied researchers.  We analyze in detail the cases of differences-in-differences withfew treated clusters, shift-share designs, weighted OLS, stratified experiments, and matching estimators.

### Analysis of residuals

#### Generalised linear models

> keywords: #regression, #linear, #residuals

Answer on Cross Validated ([Link](https://stats.stackexchange.com/a/139624))

* The standard residual plots (`plot(glm_object)`) do not make much sense with glm models, since there is no `plot.glm` method, and `plot.lm` is called.
* Short explanation of what to look at if the model was an lm object is also included.
* There are specific diagnostic plots for glm objects in the `boot`package: `glm.diag.plots`.

### Linear mixed models

> keywords: #regression, #linear, #hierarchical, #mixed

* Presentation on [Linear mixed models in R](https://athanasiamo.github.io/LME_introduction_workshop/slides/lme_UseR_Oslo_2019.html#1), by Athanasia Monika Mowinckel
* Blog post [Introduction to linear mixed models](https://gkhajduk.github.io/2017-03-09-mixed-models/), by Gabriela K. Hayduk

## Causal Inference

### Causal design patterns for data analysts

> keywords: #blog, #causal, #data, #tutorial, #R

Blog post by Emily Riederer ([Link](https://emilyriederer.netlify.app/post/causal-design-patterns/?s=09))

### Causal Inference for The Brave and True

> keywords: #book, #causal, #econometrics, #prediction, #python, #paneldata, #timeseries, #mixedmodel

Free ebook on Github pages by Matheus Facure Alves about causal inference, with code in python. ([Link](https://matheusfacure.github.io/python-causality-handbook/landing-page.html))

### We all have secret futures

> keywords: #personalizedmedicine, #philosophyofscience

Blog post by Darren Dahly ([Link](https://mdsr-book.github.io/mdsr2e/))

* "It is hopefully obvious to you that this treatment effect is not something we can actually ever know, since it’s no more possible to go back in time to change your treatment as it is to go back and zig instead of zag."
* "So there is no such thing as personalized medicine."

## Health economics

### Health Econometrics Using Stata

> keywords: #book, #econometrics, #healtcareexpenditure, #stata

[Health Econometrics Using Stata](https://www.stata.com/bookstore/health-econometrics-using-stata/) by Partha Deb, Edward C. Norton, and Willard G. Manning provides an excellent overview of the methods used to analyze data on healthcare expenditure and use. With Stata code, and data free to [download](https://www.stata-press.com/data/heus.html).

## Philsophy of science

### Error and the Growth of Experimental Knowledge

> keywords: #book

Book by Deborah G. Mayo ([Link](https://errorstatistics.files.wordpress.com/2020/10/egek-pdf-red.pdf))
